id: I5FF75F58
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T03:50:14+00:00'
last_modified: '2022-06-08T05:00:41.600601+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG23848
  title: བསླབ་པ་ཀུན་ལས་བཏུས་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    2B50:
      image_group_id: I1KG24053
      title: ''
      total_pages: 18
      order: 1
      base_file: 2B50.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
