id: I5FF75F58
legacy_id: P005572
ocr_import_info:
  bdrc_scan_id: W1KG23848
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T03:50:03'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T13:36:34.186071+00:00'
last_modified: 2022-08-31 21:36:39.092498
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG23848
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG23848
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བསླབ་པ་ཀུན་ལས་བཏུས་པ།
  author: རྒྱལ་སྲས་ཞི་བ་ལྷ།
statistics:
  ocr_word_mean_confidence_index: 0.8606498234117432
  ocr_word_median_confidence_index: 0.949999988079071
quality: null
bases:
  I1KG24053:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG24053
      total_pages: 18
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG24053.txt
    statistics:
      ocr_word_median_confidence_index: 0.949999988079071
      ocr_word_mean_confidence_index: 0.8606498234117432
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
